# =========================================
# ENUMS
# =========================================
enum RolUsuario {
  administrador
  profesor
  investigador
  empleador
  egresado
  alumno
  empresa
}

# =========================================
# TIPOS PRINCIPALES
# =========================================
type Usuario {
  idUsuario: ID!
  nombre: String!
  apellido: String
  email: String!
  telefono: String
  ubicacion: String
  rolPrincipal: RolUsuario
  completitud: Int

  adminData: Administrador
  egresadoData: Egresado
  alumnoData: Alumno
}

type Administrador {
  idUsuario: Int!
  titulo: String
  descripcion: String
}

type Egresado {
  idUsuario: Int!
  anioEgreso: Int!
  titulo: String
}

type Alumno {
  idUsuario: ID!
  carrera: String!
  semestre: Int!
  idAuditoria: Int!
  usuario: Usuario!
}

# =========================================
# PORTAFOLIO
# =========================================
type Portafolio {
  idPortafolio: Int!
  idUsuario: Int!
  descripcion: String
  skills: String
  visibilidad: String
  ultimaActualizacion: String
  evidencias: [Evidencia!]!
}

type Evidencia {
  idEvidencia: Int!
  idPortafolio: Int!
  titulo: String
  descripcion: String
  tipo: String
  recurso: String
}

# =========================================
# QUERIES
# =========================================
type Query {
  alumnos: [Alumno!]!
  alumno(id: ID!): Alumno
  alumnoPorEmail(email: String!): Alumno

  usuarioById(id: Int!): Usuario
  usuarios: [Usuario!]!

  portafolioPorUsuario(idUsuario: Int!): Portafolio
}

# =========================================
# INPUTS
# =========================================
input UsuarioInput {
  nombre: String
  apellido: String
  email: String
  telefono: String
  ubicacion: String
}

input AlumnoInput {
  usuario: UsuarioInput
  carrera: String
  semestre: Int
}

input UsuarioRegistroInput {
  nombre: String!
  apellido: String
  email: String!
  telefono: String
  ubicacion: String
  password: String!
  rolPrincipal: RolUsuario = alumno
  completitud: Int = 0
}

input RegistroAlumnoInput {
  usuario: UsuarioRegistroInput!
  carrera: String!
  semestre: Int!
  detalleAuditoria: String = "registro alumno"
}

input LoginInput {
  email: String!
  password: String!
}

# =========================================
# LOGIN RESPONSE
# =========================================
type LoginResponse {
  idUsuario: ID!
  nombre: String
  apellido: String
  rolPrincipal: RolUsuario
}

# =========================================
# INPUT EGRESADO
# =========================================
input EgresadoInput {
  anioEgreso: Int
  titulo: String
}

# =========================================
# MUTATIONS
# =========================================
type Mutation {
  registrarAlumno(input: RegistroAlumnoInput!): Alumno
  actualizarAlumno(id: ID!, input: AlumnoInput): Alumno
  login(input: LoginInput!): LoginResponse

  actualizarEgresado(id: Int!, input: EgresadoInput!): Egresado
}
