enum RolUsuario { administrador profesor investigador egresado alumno empresa }

type Usuario {
  idUsuario: ID!
  nombre: String!
  apellido: String
  email: String!
  telefono: String
  ubicacion: String
  rolPrincipal: RolUsuario
}

type Alumno {
  idAlumno: ID!
  usuario: Usuario!
  carrera: String
  semestre: Int
}

input UsuarioRegistroInput {
  nombre: String!
  apellido: String
  email: String!
  telefono: String
  ubicacion: String
  password: String!
}
# --- Queries ---
type Query {
  alumnos: [Alumno!]!
  alumno(id: ID!): Alumno
  alumnoPorEmail(email: String!): Alumno
}

input RegistroAlumnoInput {
  usuario: UsuarioRegistroInput!
  carrera: String
  semestre: Int
}

input AlumnoInput {
  idAlumno: ID!
  carrera: String
  semestre: Int
}

input LoginInput {
  email: String!
  password: String!
}

type LoginResponse {
  idUsuario: ID!
  nombre: String
  apellido: String
  rolPrincipal: RolUsuario
}

type Mutation {
  registrarAlumno(input: RegistroAlumnoInput!): Alumno
  actualizarAlumno(input: AlumnoInput!): Alumno
  login(input: LoginInput!): LoginResponse
}
