spring.application.name=backend
spring.docker.compose.enabled=false

# --- Datasource ---
spring.datasource.url=jdbc:postgresql://localhost:5432/vias_uc_docentes
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
# En dev pod�s usar update. En prod: validate.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# --- GraphQL ---
spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql


