spring.application.name=backend
spring.docker.compose.enabled=false

# --- Datasource (SERVER) ---
spring.datasource.url=jdbc:postgresql://34.95.213.224:5432/postgres?currentSchema=public&sslmode=require
spring.datasource.username=postgres
spring.datasource.password=UniversidadCatolica2025*
spring.datasource.driver-class-name=org.postgresql.Driver
# Pool recomendado
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# --- JPA / Hibernate ---
# En server: NO tocar esquema
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.type.preferred_enum_type=postgres_enum

spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false

# --- GraphQL ---
spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
