spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vias_uc_docentes
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate  # solo valida que las tablas existen
    show-sql: true
  graphql:
    schema:
      printer:
        enabled: true
